# This is a basic workflow to help you get started with Actions

name: check-link-validity

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
    pull_request_target:
      types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check validity
        uses: Chen-Zidi/check-modified-contents-link-validity-action@main
        id: check-validity

      # Runs a single command using the runners shell
      - name: print validity result
        run: echo "validity - ${{ steps.check-validity.outputs.validity}}"
